version: '2'
services:
  admin:
    build:
      context: .
    working_dir: /deploy/admin
    volumes:
      - ./admin:/deploy/admin
      - ./users.db:/deploy/users.db
    networks:
      - web_nw
  user:
    build: 
      context: .
    working_dir: /deploy/user
    volumes:
      - ./user:/deploy/user
      - ./users.db:/deploy/users.db
    networks:
      - web_nw
  nginx:
    image: "nginx:mainline"
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d
    environment:
      - net.ipv6.conf.all.forwarding=1
    ports:
      - "80:80"
      - "9000:9000"
    depends_on:
      - user
      - admin
    networks:
      - web_nw
networks:
  web_nw:
    driver: bridge
